2021-01-02 13:42:24.207 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bloomFilterTask' defined in file [/Users/youxuehu/IdeaProjects/springboot-demo/target/classes/com/example/springbootdemo/init/BloomFilterTask.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.example.springbootdemo.SpringbootDemoApplication.main(SpringbootDemoApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NullPointerException: null
	at com.example.springbootdemo.bloomFilter.BloomFilter.hash(BloomFilter.java:135)
	at com.example.springbootdemo.bloomFilter.BloomFilter.add(BloomFilter.java:66)
	at com.example.springbootdemo.init.BloomFilterTask.lambda$afterPropertiesSet$0(BloomFilterTask.java:22)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.example.springbootdemo.init.BloomFilterTask.afterPropertiesSet(BloomFilterTask.java:21)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 21 common frames omitted
2021-01-02 13:44:39.469 [QuartzScheduler_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 1hge2niae1hq1o4l1rsbk9w|4d80168d, dataSourceName -> 1hge2niae1hq1o4l1rsbk9w|4d80168d ] has been closed() -- you can no longer use it.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3861)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 1hge2niae1hq1o4l1rsbk9w|4d80168d, dataSourceName -> 1hge2niae1hq1o4l1rsbk9w|4d80168d ] has been closed() -- you can no longer use it.
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:512)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:524)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.quartz.utils.C3p0PoolingConnectionProvider.getConnection(C3p0PoolingConnectionProvider.java:223)
	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780)
	... 4 common frames omitted
2021-01-02 13:44:39.469 [QuartzScheduler_QuartzScheduler-NON_CLUSTERED_MisfireHandler] ERROR org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: Error handling misfires: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3246)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:694)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.quartz.utils.C3p0PoolingConnectionProvider.getConnection(C3p0PoolingConnectionProvider.java:223)
	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780)
	... 4 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1503)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 8 common frames omitted
2021-01-02 13:51:50.438 [http-nio-9090-exec-7] ERROR c.e.springbootdemo.controller.LoginController - 该用户不存在（未通过布隆过滤器）
2021-01-02 13:51:50.439 [http-nio-9090-exec-7] ERROR c.example.springbootdemo.controller.BaseController - {
	"success":false,
	"errorMessage":"该用户不存在（未通过布隆过滤器）"
}
2021-01-02 13:52:54.295 [http-nio-9090-exec-1] ERROR c.e.springbootdemo.controller.LoginController - 该用户不存在（未通过布隆过滤器）
2021-01-02 13:52:54.296 [http-nio-9090-exec-1] ERROR c.example.springbootdemo.controller.BaseController - {
	"success":false,
	"errorMessage":"该用户不存在（未通过布隆过滤器）"
}
2021-01-02 13:53:03.008 [http-nio-9090-exec-8] ERROR c.e.springbootdemo.controller.LoginController - 该用户不存在（未通过布隆过滤器）
2021-01-02 13:53:03.008 [http-nio-9090-exec-8] ERROR c.example.springbootdemo.controller.BaseController - {
	"success":false,
	"errorMessage":"该用户不存在（未通过布隆过滤器）"
}
2021-01-02 13:53:50.726 [QuartzScheduler_QuartzScheduler-NON_CLUSTERED_MisfireHandler] ERROR org.quartz.impl.jdbcjobstore.JobStoreTX - MisfireHandler: Error handling misfires: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 1hge2niae1hqd5ys2u7bkd|1a7b347c, dataSourceName -> 1hge2niae1hqd5ys2u7bkd|1a7b347c ] has been closed() -- you can no longer use it.
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'qzDS': java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 1hge2niae1hqd5ys2u7bkd|1a7b347c, dataSourceName -> 1hge2niae1hqd5ys2u7bkd|1a7b347c ] has been closed() -- you can no longer use it.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3246)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLException: com.mchange.v2.c3p0.ComboPooledDataSource[ identityToken -> 1hge2niae1hqd5ys2u7bkd|1a7b347c, dataSourceName -> 1hge2niae1hqd5ys2u7bkd|1a7b347c ] has been closed() -- you can no longer use it.
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:512)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:524)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.quartz.utils.C3p0PoolingConnectionProvider.getConnection(C3p0PoolingConnectionProvider.java:223)
	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:780)
	... 4 common frames omitted
2021-01-02 13:54:08.868 [http-nio-9090-exec-7] ERROR c.e.springbootdemo.controller.LoginController - 该用户不存在（未通过布隆过滤器）
2021-01-02 13:54:08.870 [http-nio-9090-exec-7] ERROR c.example.springbootdemo.controller.BaseController - {
	"success":false,
	"errorMessage":"该用户[160000000001]不存在（未通过布隆过滤器）"
}
